<header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>S</b>Pym</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Si</b>Pyme</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->

              <!-- Notifications Menu -->
              
              <!-- Tasks Menu -->
              
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <?php echo Html::img("upload/personas/".Session::get('fotografia'), 'Imagen de usuario', 'class="user-image"')?>
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs"><?php echo Session::get('nombre').' '.Session::get('apellido'); ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <?php echo Html::img("upload/personas/".Session::get('fotografia'), 'Imagen de usuario', 'class="img-circle"')?><br>
                    <p>
                      <?php echo Session::get('nombre').' '.Session::get('apellido'); ?> <br> <?php echo "Web Developer"; ?> 
                      <?php 
                        $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado"); 
                        $mes = array("0","Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
                      ?>
                      <small><?php echo "Hoy es ".$dias[date('w')]." ".date('d')." de ".$mes[date('n')]." del ".date('Y'); ?></small><br>
                    </p>
                  </li>
                  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <?php echo DwHtml::link('sistema/mi_cuenta/', 'Mi Cuenta', array('class'=>'btn btn-default btn-flat'), 'fa-user'); ?>
                    </div>
                    <div class="pull-right">
                      <?php echo DwHtml::link('login/salir/', 'Salir', array('class'=>'no-load btn btn-default btn-flat'), 'fa-power-off', FALSE); ?>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>