<aside class="main-sidebar">
        <?php DwMenu::load(Menu::BACKEND, Session::get('perfil_id')); ?>
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <?php echo Html::img("upload/personas/".Session::get('fotografia'), 'Imagenes', 'class="img-circle"')?>
            </div>
            <div class="pull-left info">
              <p><?php echo Session::get('nombre').' '.Session::get('apellido'); ?></p>
              <!-- Status -->
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

          <!-- search form (Optional) -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..." />
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->

          <!-- Sidebar Menu -->
          <?php echo DwMenu::AdminLTE(); ?>

        </section>
        <!-- /.sidebar -->
      </aside>