<section class="content-header">
    <?php if(!empty($titulo)) { ?>
    <script type="text/javascript">        
        changeTitle('<?php echo $proceso; ?>');
        <?php 
        
        if(Session::get('change_url') === TRUE) {             
            Session::set('change_url', FALSE);
            extract(Router::get());
            $url = "$controller/$action";
            if($module) {
                $url = "$module/$url";
            }
            if($parameters) {
                $params = join('/', $parameters);
                $params = explode('page.', $params);
                if($params[0]) {
                    $url = "$url/".trim($params[0], '/');
                }
            }
            $url = rtrim($url, '/').'/';
            ?>            
            try {
                updateUrl('<?php echo $url; ?>');
            } catch(e) {

            }
            <?php
        }
        ?>
       
    </script>
    <?php } ?>
    
    <?php 
    if(isset($proceso) && $proceso!=null) 
        { 
            $proceso = explode(' |', $proceso); 
             $page_title = $proceso[0];
        } 
    ?>
    <h1>
        <?php echo ucfirst($modulo); ?>
        <?php echo " <small>",ucfirst(trim($page_title)),"</small>"; ?>
    </h1>
<!--    <ol class="breadcrumb">
        <li><?php // echo Html::link('dashboard', '<i class="fa fa-dashboard"></i> Inicio') ?></li>
        <li class="active"><?php // echo $page_title; ?></li>
    </ol>-->
</section>