<?php // Tag::css('AdminLTE/plugins/select2/select2.min').PHP_EOL ?>
<?php // echo Html::includeCss(); ?>
<?php echo Ajax::form('myModal', "almacen/productos/create", 'form-horizontal', 'post', 'role="form"')?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="productos_codigo" class="col-lg-3 control-label">Codigo</label>
                        <div class="col-lg-8">
                            <?php echo Form::text('productos.codigo', 'class="form-control" placeholder="Codigo de barras" required', NULL)?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="productos_prod_descrip" class="col-lg-3 control-label">Descripción</label>
                        <div class="col-lg-8">
                            <?php echo Form::textarea('productos.prod_descrip', 'class="form-control" placeholder="Descripcion del producto" required', NULL)?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="productos_unidadesm_id" class="col-lg-3">Unidad de Medida</label>
                        <div class="col-lg-8">
                            <?php echo Form::dbSelect('productos.unidadesm_id', 'unidad_nombre', array('catalogos/unidadesm','buscarUnidadM'), '-- Seleccione --', 'class="form-control"') ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="productos_tipoproducto_id" class="col-lg-3">Tipo de producto</label>
                        <div class="col-lg-8">
                            <?php echo Form::dbSelect('productos.tipoproducto_id', 'tipoproducto_nombre', array('catalogos/tipoproducto','buscarTipoP'), '-- Seleccione --', 'class="form-control"') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <?php echo Form::button('Cerrar', 'class="btn btn-default pull-left" data-dismiss="modal"') ?>
            <?php echo Form::submit('Guardar', 'class="btn btn-primary"') ?>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<?php echo Form::close(); ?>
<?php // echo Tag::js('AdminLTE/plugins/select2/select2.min').PHP_EOL; ?>
<!--<script type="text/javascript">
    $(function () {
        $(".select2").select2();
    });
</script>-->