<?php Tag::css('AdminLTE/plugins/datatables/dataTables.bootstrap').PHP_EOL ?>
<?php echo Html::includeCss(); ?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    
    <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        
    <?php View::flash(); ?>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">
                            <?php echo Ajax::link('almacen/productos/create', '<i class="fa fa-plus"></i> Nuevo Producto', 'myModal', 'btn btn-primary btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                        </h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="tableProductos" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Clave</th>
                                    <th>Codigo</th>
                                    <th>Descripción</th>
                                    <th>Unidad</th>
                                    <th>Tipo</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                           
                            <tbody>
                                 <?php foreach ($productos as $producto) :?>
                                <tr>
                                    <td><?php echo $producto->id ?></td></td>
                                    <td><?php echo $producto->codigo ?></td>
                                    <td><?php echo $producto->prod_descrip ?></td>
                                    <td><?php echo $producto->unidad_nombre ?></td>
                                    <td><?php echo $producto->tipoproducto_nombre ?></td>
                                    <td>
                                        <?php echo Ajax::link("almacen/productos/edit/$producto->id", '<i class="fa fa-edit"></i> Editar', 'myModal', 'btn btn-default btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>  
                    </div>
                </div>
            </div>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
        </div>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<!-- Data Table -->
<?php echo Tag::js('AdminLTE/plugins/datatables/jquery.dataTables.min').PHP_EOL; ?>
<?php echo Tag::js('AdminLTE/plugins/datatables/dataTables.bootstrap.min').PHP_EOL; ?>
<script type="text/javascript">
    $(function () {
        $("#tableProductos").DataTable({
            responsive: true,
            "oLanguage": {
                "sUrl": "<?php echo PUBLIC_PATH; ?>javascript/AdminLTE/plugins/datatables/datatable.espanol.txt"	
            },
            "aaSorting":[[3,"asc"]]
        });
    });
</script>
