<?php Tag::css('validation/validationEngine.jquery').PHP_EOL ?>
<?php echo Html::includeCss(); ?>
<?php echo Form::open('config/empresas/create', 'post', 'role="form" class="form-horizontal" id="empresas-val"')?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        
    <?php View::flash(); ?>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">
                            <?php // echo Ajax::link('config/empresas/create', '<i class="fa fa-plus"></i> Agregar Empresa', 'myModal', 'btn btn-primary btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                        </h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="empresas_e_nombrecorto" class="col-lg-4 control-label">Nombre corto</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('empresas.e_nombrecorto', 'class="validate[required] form-control" placeholder="Nombre de empresa"', NULL)?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="empresas_e_razonsocial" class="col-lg-4 control-label">Razon Social</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('empresas.e_razonsocial', 'class="validate[required] form-control" placeholder="Razon social"', NULL)?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="empresas_e_rfc" class="col-lg-4 control-label">R.F.C.</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('empresas.e_rfc', 'class="validate[required,custom[rfc]] form-control" placeholder="R.F.C. de la empresa"', NULL)?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="col-md-12">
                                        <div class="row fileupload-buttonbar">
                                            <!--<div class="col-md-6" style="margin-bottom: 20px;">-->
                                                <div class="row">
                                                    <div class="col-md-8">
                                                        <?php echo DwForm::upload('logotipo', array('data-to'=>PUBLIC_PATH.'config/empresas/upload/', 'data-size'=>5000000, 'data-files'=>'images', 'data-success'=>'loadImg'), ' Agregar Logotipo'); ?>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <div class="picture-profile text-center text-middle shadow-dark" style="margin: 5px auto 0px;">
                                                            <?php echo DwHtml::img("upload/empresas/default.png", "Logotipo", array('id'=>'img-empresa')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                        <!--</div>-->
                                        <?php echo DwForm::hidden('empresas.e_logo', NULL, 'default.png'); ?>
                                        </div> 
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
                    <div class="box-footer clearfix">
                        <?php echo DwForm::cancel(); ?>
                        <?php echo Form::submit('Guardar', 'class="btn btn-primary pull-right"') ?>
                    </div>    
                </div>
            </div>
        </div>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->


<?php echo Form::close(); ?>
<?php echo Tag::js('validation/jquery.validationEngine-es').PHP_EOL; ?>
<?php echo Tag::js('validation/jquery.validationEngine').PHP_EOL; ?>
<script type="text/javascript">
    
    function loadImg(result, input) {
        $("#empresas_e_logo").val(result.name);
        $("#img-empresa").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/empresas/'+result.name);                
    }
    
    $("#empresas-val").validationEngine('attach', {promptPosition : "centerRight", scroll: false});
</script>