<?php echo Ajax::form('myModal', "catalogos/bancos/create", 'form-horizontal', 'post', 'role="form"')?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="bancos_b_clave" class="col-lg-4 control-label">Clave SAT</label>
                        <div class="col-lg-8">
                            <?php echo Form::text('bancos.b_clave', 'class="form-control" placeholder="Clave con identificacion ante SAT" required', NULL)?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bancos_b_nombrecorto" class="col-lg-4 control-label">Nombre corto</label>
                        <div class="col-lg-8">
                            <?php echo Form::text('bancos.b_nombrecorto', 'class="form-control" placeholder="Nombre de monda" required', NULL)?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bancos_b_razonsocial" class="col-lg-4 control-label">Razon Social</label>
                        <div class="col-lg-8">
                            <?php echo Form::text('bancos.b_razonsocial', 'class="form-control" placeholder="Nombre de monda" required', NULL)?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bancos_b_estatus" class="col-lg-4 control-label">Estatus</label>
                        <div class="col-lg-8">
                            <?php echo Form::select('bancos.b_estatus', $estatus, 'class="form-control" required')?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <?php echo Form::button('Cerrar', 'class="btn btn-default pull-left" data-dismiss="modal"') ?>
            <?php echo Form::submit('Guardar', 'class="btn btn-primary"') ?>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<?php echo Form::close(); ?>