<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    
    <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        
    <?php View::flash(); ?>
    <!-- Main content -->
    <section class="content">
        <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Pagina principal</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    
                </div>
        </div>
          <!-- Your Page Content Here -->
        
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->