<?php Tag::css('AdminLTE/plugins/datatables/dataTables.bootstrap').PHP_EOL ?>
<?php echo Html::includeCss(); ?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    
    <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        
    <?php View::flash(); ?>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">
                            <?php echo Ajax::link('catalogos/tipoproducto/create', '<i class="fa fa-plus"></i> Agregar Unidad', 'myModal', 'btn btn-primary btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                        </h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="tableTipoproducto" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Clave</th>
                                    <th>Tipo Prodcuto</th>
                                    <th>Estatus</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                           
                            <tbody>
                                 <?php foreach ($tipoproducto as $tp) :?>
                                <tr>
                                    <td><?php echo $tp->id ?></td>
                                    <td><?php echo $tp->tipoproducto_nombre ?></td>
                                    <td>
                                        <?php 
                                            if ($tp->tip_estatus == "activa"){
                                                echo '<small class="label bg-green bg">'.$tp->tip_estatus.'</small>';
                                            }else{
                                                echo '<small class="label bg-red">'.$tp->tip_estatus.'</small>';
                                            }
                                             
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo Ajax::link("catalogos/tipoproducto/edit/$tp->id", '<i class="fa fa-edit"></i> Editar', 'myModal', 'btn btn-default btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                                    </td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>  
                    </div>
                </div>
            </div>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
        </div>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<!-- Data Table -->
<?php echo Tag::js('AdminLTE/plugins/datatables/jquery.dataTables.min').PHP_EOL; ?>
<?php echo Tag::js('AdminLTE/plugins/datatables/dataTables.bootstrap.min').PHP_EOL; ?>
<script type="text/javascript">
    $(function () {
        $("#tableTipoproducto").DataTable({
            responsive: true,
            "oLanguage": {
                "sUrl": "<?php echo PUBLIC_PATH; ?>javascript/AdminLTE/plugins/datatables/datatable.espanol.txt"	
            },
            "aaSorting":[[1,"asc"]]
        });
    });
</script>