<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
  <head>
    <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
        <meta name="robots" content="noindex,nofollow" /> 
        <link rel="shortcut icon" href="<?php echo PUBLIC_PATH; ?>img/favicon.ico" type="image/x-icon" />
    <!-- Bootstrap 3.3.4 -->
    <?php Tag::css('AdminLTE/bootstrap/css/bootstrap.min').PHP_EOL ?>
    <!-- Font Awesome Icons -->
    <?php Tag::css('font-awesome-4.3.0/css/font-awesome.min').PHP_EOL ?>
    <!-- Ionicons -->
    <?php Tag::css('ionicons-2.0.1/css/ionicons.min').PHP_EOL ?>
    <!-- File upload -->
    <?php Tag::css('file-upload/jquery.fileupload'); ?>
    <?php Tag::css('file-upload/jquery.fileupload-ui'); ?>
    <!-- Theme style -->
    <?php Tag::css('AdminLTE/dist/css/AdminLTE.min').PHP_EOL ?>
    <!-- Skin -->
    <?php Tag::css('AdminLTE/dist/css/skins/skin-blue').PHP_EOL ?>

    <?php echo Html::includeCss(); ?>
    
    <style type="text/css">
        <?php if(APP_MAYUS) { ?>            
            .input-lower, .input-email, email, .mask-email, .js-datepicker { text-transform: none !important; font-size: 14px !important}
            textarea, select, input[type="text"], input[type="search"], .uneditable-input { text-transform: uppercase; font-size: 13px }
        <?php } ?>                          
    </style>
    <!-- jQuery 2.1.4 -->
    <?php echo Tag::js('AdminLTE/plugins/jQuery/jQuery-2.1.4.min'); ?>
    <?php // echo Tag::js('jquery/jquery.min').PHP_EOL; ?>  
    
    <!-- File upload -->
    <?php echo Tag::js('jquery/ui/jquery.ui.widget').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery-file-upload/jquery.iframe-transport').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload-fp').PHP_EOL; ?>        
    <?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload-ui').PHP_EOL; ?>
       
    <!--[if gte IE 8]><?php echo Tag::js('jquery/jquery-file-upload/cors/jquery.xdr-transport'); ?><![endif]-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        function changeTitle(title) { if($(document).attr('title') != title) { $(document).attr('title', title); } }
    </script>
  </head>
  
  <body class="skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <?php View::partial('AdminLTE/header') ?>
      <!-- Left side column. contains the logo and sidebar -->
      <?php View::partial('AdminLTE/menu') ?>

      <!-- Your Page Content Here -->
      <?php View::content(); ?>
        
      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
          Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
      </footer>

      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    <!-- REQUIRED JS SCRIPTS -->

    
    <!-- Bootstrap 3.3.2 JS -->
    <?php echo Tag::js('AdminLTE/bootstrap/js/bootstrap.min'); ?>
    
    <?php echo Tag::js('jquery/jquery.kumbiaphp').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.keyfilter').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kgrid').PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kload').PHP_EOL; ?>        
    <?php echo Tag::js('jquery/jquery.spin').PHP_EOL; ?>        
    <?php echo Tag::js('html5shiv').PHP_EOL; ?>        
    
    <?php echo Tag::js('backend').PHP_EOL; ?>
    <?php echo Tag::js('validador').PHP_EOL; ?>
    <!-- AdminLTE App -->
    <?php echo Tag::js('AdminLTE/dist/js/app.min'); ?>
    
  </body>
</html>
