<?php Tag::css('validation/validationEngine.jquery').PHP_EOL ?>
<?php echo Html::includeCss(); ?>
<?php echo Form::open('config/proveedores/create', 'post', 'role="form" class="form-horizontal" id="proveedores-val"')?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <?php View::processAdminLTE($page_module, $page_title, $set_title); ?>
        
    <?php View::flash(); ?>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">
                            <?php // echo Ajax::link('config/empresas/create', '<i class="fa fa-plus"></i> Agregar Empresa', 'myModal', 'btn btn-primary btn-flat', 'data-toggle="modal" data-target="#myModal"')?>
                        </h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-lg-6">
                            <div class="row">
                                <!--<div class="col-lg-6">-->
                                    <div class="form-group">
                                        <label for="proveedores_p_nombrecorto" class="col-lg-4 control-label">Nombre corto</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('proveedores.p_nombrecorto', 'class="validate[required] form-control" placeholder="Nombre del proveedor"', NULL)?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="proveedores_p_razonsocial" class="col-lg-4 control-label">Razon Social</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('proveedores.p_razonsocial', 'class="validate[required] form-control" placeholder="Razon social"', NULL)?>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="proveedores_p_rfc" class="col-lg-4 control-label">R.F.C.</label>
                                        <div class="col-lg-8">
                                            <?php echo Form::text('proveedores.p_rfc', 'class="validate[required,custom[rfc]] form-control" placeholder="R.F.C. del proveedor"', NULL)?>
                                        </div>
                                    </div>
                                <!--</div>-->
                            </div>  
                        </div>
                    </div>
                    <div class="box-footer clearfix">
                        <?php echo DwForm::cancel(); ?>
                        <?php echo Form::submit('Guardar', 'class="btn btn-primary pull-right"') ?>
                    </div>    
                </div>
            </div>
        </div>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->


<?php echo Form::close(); ?>
<?php echo Tag::js('validation/jquery.validationEngine-es').PHP_EOL; ?>
<?php echo Tag::js('validation/jquery.validationEngine').PHP_EOL; ?>
<script type="text/javascript">
    $("#proveedores-val").validationEngine('attach', {promptPosition : "centerRight", scroll: false});
</script>